version: "3"

# volumes:
#   mariadbvol:

services:
  # transticlock-db:
  #   image: mariadb:10
  #   container_name: transticlock-db
  #   restart: unless-stopped
  #   ports:
  #     - 3336:3306
  #   volumes:
  #     - mariadbvol:/var/lib/mysql
  #   environment:
  #     - MARIADB_ROOT_PASSWORD=${DB_PASS}
  tt-tioenvigado:
    image: transitclock-muuf:06052023-5
    container_name: tt-tioenvigado
    restart: unless-stopped
    ports:
      - 8081:8080
    volumes:
      - ./logs/tt-tioenvigado:/usr/local/transitclock/logs/
      - ./ehcache/tt-tioenvigado:/usr/local/transitclock/cache/
      # - ./bin:/usr/local/transitclock/bin/
      # - ./config/transitclock.properties:/usr/local/transitclock/config/transitclock.properties
      # - ./config/postgres_hibernate.cfg.xml:/usr/local/transitclock/config/hibernate.cfg.xml
    environment:
      - DB_USER=${DB_USER}
      - MYSQL_PWD=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - AGENCYNAME=tioenvigado
      - AGENCYID=93
      - GTFS_URL=${GTFSSTATICFILE}/gtfs_tio_envigado.zip
      - GTFSRTVEHICLEPOSITIONS=${GTFSRTVEHICLEPOSITIONS}/93
    command: start_transitclock.sh
  tt-combuses:
    image: transitclock-muuf:02052023
    container_name: tt-combuses
    restart: unless-stopped
    ports:
      - 8082:8080
    volumes:
      - ./logs/tt-combuses:/usr/local/transitclock/logs/
      - ./ehcache/tt-combuses:/usr/local/transitclock/cache/
    environment:
      - DB_USER=${DB_USER}
      - MYSQL_PWD=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - AGENCYNAME=combuses
      - AGENCYID=173
      - GTFS_URL=${GTFSSTATICFILE}/gtfs_combuses.zip
      - GTFSRTVEHICLEPOSITIONS=${GTFSRTVEHICLEPOSITIONS}/173
    command: start_transitclock.sh
  tt-sotrames:
    image: transitclock-muuf:02052023
    container_name: tt-sotrames
    restart: unless-stopped
    ports:
      - 8083:8080
    volumes:
      - ./logs/tt-sotrames:/usr/local/transitclock/logs/
      - ./ehcache/tt-sotrames:/usr/local/transitclock/cache/
    environment:
      - DB_USER=${DB_USER}
      - MYSQL_PWD=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - AGENCYNAME=sotrames
      - AGENCYID=95
      - GTFS_URL=${GTFSSTATICFILE}/gtfs_sotrames.zip
      - GTFSRTVEHICLEPOSITIONS=${GTFSRTVEHICLEPOSITIONS}/95
    command: start_transitclock.sh
  tt-autobuses_p:
    image: transitclock-muuf:02052023
    container_name: tt-autobuses_p
    restart: unless-stopped
    ports:
      - 8084:8080
    volumes:
      - ./logs/tt-autobuses_p:/usr/local/transitclock/logs/
      - ./ehcache/tt-autobuses_p:/usr/local/transitclock/cache/
    environment:
      - DB_USER=${DB_USER}
      - MYSQL_PWD=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - AGENCYNAME=autobuses_p
      - AGENCYID=85
      - GTFS_URL=${GTFSSTATICFILE}/gtfs_autobuses_el_poblado_laureles.zip
      - GTFSRTVEHICLEPOSITIONS=${GTFSRTVEHICLEPOSITIONS}/85
    command: start_transitclock.sh
