version: "3"

volumes:
  posgtgresvol:

services:
  transticlock-db:
    image: postgres:9.6
    container_name: transticlock-db
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - posgtgresvol:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${PGPASSWORD}
